version: "3"
services:
 
  redis:
    image: redis:6.2.7
    ports:
      - "6379"
    networks:
      - snet
  
  app:
    build: .
    ports:
      - "18080"
    networks:
      - snet
    volumes:
      - ./src:/app
      - D:\data\containerControlFiles:/mnt
 
networks:
  snet:
    driver: bridge

 