// Code generated by hertz generator.

package main

import (
	handler "github.com/bnc1010/containerManager/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.POST("/postping", handler.PostTest)
	r.POST("/common/postping", handler.CommonPostTest)
	r.POST("/admin/postping", handler.AdminPostTest)
	r.POST("/root/postping", handler.RootPostTest)
	// your code ...
}
