App:
  HostPorts: 0.0.0.0:8888
  MaxRequestBodySize: 20971520  # 20M
  TokenHeader: AUTH_TOKEN       # 请求头中token的字段名

Cronjob:
  TempFileMinute: 1440
  TokenMinute: 55

Redis:
  Addr: "redis:6379"           # 新建一个docker网络，非则不能以容器命访问
  Password: ""
  Db: 1