App:
  HostPorts: 127.0.0.1:8888
  MaxRequestBodySize: 20971520  # 20M
  TokenHeader: AUTH_TOKEN       # 请求头中token的字段名

Cronjob:
  TempFileMinute: 1440
  TokenMinute: 55

Redis:
  Addr: "172.25.192.1:6379"
  Password: ""
  Db: 1